### PR TITLE
Adding graph-quilt/graphql-orchestrator-java

### PR DESCRIPTION
**Pull request by ashpak-shaikh**
Adding graphql-orchestrator-java project that uses the graphql-java execution strategy for orchestrating queries to multiple backends.

### CODE REVIEW

**Review by setchy — APPROVED** [review]

**Comment by setchy** [comment]
@ashpak-shaikh - you may also like to add this to https://github.com/chentsulin/awesome-graphql#java :)

**Comment by ashpak-shaikh** [comment]
@setchy Thanks for the approval. Would you be able to merge it as well ?
 
Also, thanks for referencing the other git as well. 
Created https://github.com/chentsulin/awesome-graphql/pull/719

**Comment by setchy** [comment]
I don't have `merge` rights here unfortunately.  I can help with the other repo though

**Comment by ashpak-shaikh** [comment]
@bbakerman Can you review and merge this PR ?

**Comment by bbakerman** [comment]
Currently on vacation...but will when I get back

**Pull request merged**
